// generated by wxGlade 0.6.8 on Wed May 20 12:40:03 2015

#ifndef WXGUI_HPP
#define WXGUI_HPP

#include <map>
#include <wx/wx.h>
#include <wx/image.h>
#include "wx/intl.h"

#include "crossgen.hpp"

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


class MainFrame: public wxFrame {
public:
    // begin wxGlade: MainFrame::ids
    // end wxGlade

    MainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MainFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    std::vector<wxString> _words;
    DictType _dict;
    bool _isDictLoaded;
    AllWordsType _allWords;
    CharsTransType _transType;
    // begin wxGlade: MainFrame::attributes
    wxStaticText* label_1;
    wxTextCtrl* tPath;
    wxButton* btnPath;
    wxTextCtrl* tOutput;
    wxButton* btnGenerate;
    wxStaticBitmap* bPreview;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnbtnPathClick(wxCommandEvent &event); 
    virtual void OnbtnGenerateClick(wxCommandEvent &event); 
    void SetGridImage(GridType &grid, size_t w=400);
}; // wxGlade: end class


#endif // WXGUI_HPP
